version: '3'
services:
  app:
    build:
      context: .
    volumes:
      - ./src:/app/src
      - ./scripts:/app/scripts
      - ./data:/app/data
      - ./raw_data:/app/raw_data  # Specify raw data path (i.e. /path/to/data:/app/raw_data), or delete this line
    stdin_open: true
    tty: true
    ports:
      - 8888:8888
