name: par2_paper
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11.6
  - numpy
  - matplotlib
  - ipywidgets
  - ipympl
  - jupyter
  - scipy
  - pandas
  - seaborn=0.11.0
  - jax
  - optax
  - tensorflow>=2.9.1
  - scikit-image
  - tqdm
  - sympy
  - scikit-learn
  - pip
  - pip:
      - opencv-python
      - discco==0.2.7
      - par-segmentation==0.1.12
      - saibr==0.1.6
      - matplotlib-polyroi==0.1.6
