name: par2_paper
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - numpy=1.21.6
  - matplotlib=3.3.4
  - ipywidgets=7.5.1
  - jupyter=1.0.0
  - scipy=1.7.3
  - pandas=1.3.4
  - seaborn=0.11.0
  - jax=0.3.25
  - optax=0.1.4
  - scikit-image==0.14.2
  - tqdm=4.55.2
  - pip
  - pip:
      - discco==0.1.0
