name: par2_paper
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7.9
  - numpy=1.21.6
  - matplotlib=3.5.3
  - ipywidgets=8.0.6
  - ipympl=0.9.3
  - jupyter=1.0.0
  - scipy=1.7.3
  - pandas=1.3.4
  - seaborn=0.11.0
  - jax=0.3.25
  - optax=0.1.4
  - tensorflow=2.9.1
  - scikit-image=0.14.2
  - tqdm=4.55.2
  - sympy=1.6.2
  - pip
  - pip:
      - opencv-python==4.2.0.34
      - discco==0.2.6
      - par-segmentation==0.1.8
      - saibr==0.1.4
      - matplotlib-polyroi==0.1.3
